//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Chess')
export class ChessEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  gameId: number;

  @Column('integer', { nullable: true })
  player1Name: number;

  @Column('integer', { nullable: true })
  player2Name: number;

  @Column('integer', { nullable: true })
  winnerName: number;

  @Column('real', { nullable: true })
  gameDuration: number;

  @Column('date', { nullable: true })
  datePlayed: Date;

  @Column('integer', { nullable: true })
  monthlyRanking: number;
}
