//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Lottery')
export class LotteryEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  ticketNumber: number;

  @Column('date', { nullable: true })
  drawDate: Date;

  @Column('real', { nullable: true })
  prizeAmount: number;

  @Column('integer', { nullable: true })
  winner: number;
}
