//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const ChessTitle = () => {
  const record = useRecordContext();
  return <span>Chess {record ? `"${record.gameId}"` : ''}</span>;
};

export const ChessList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="gameId" />
      <ReferenceField source="player1Name" reference="Players" />
      <ReferenceField source="player2Name" reference="Players" />
      <ReferenceField source="winnerName" reference="Players" />
      <NumberField source="gameDuration" />
      <DateField source="datePlayed" />
      <NumberField source="monthlyRanking" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const ChessEdit = () => (
  <Edit title={<ChessTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="gameId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player1Name" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player2Name" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="winnerName" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="gameDuration" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="datePlayed" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="monthlyRanking" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const ChessCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="gameId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player1Name" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="player2Name" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="winnerName" reference="Players" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="gameDuration" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="datePlayed" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="monthlyRanking" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="player1Name"
    label="player1Name"
    reference="Players"
    alwaysOn
  />,
  <ReferenceInput
    source="player2Name"
    label="player2Name"
    reference="Players"
    alwaysOn
  />,
  <ReferenceInput
    source="winnerName"
    label="winnerName"
    reference="Players"
    alwaysOn
  />,
  ,
  ,
  ,
];
