//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const LotteryTitle = () => {
  const record = useRecordContext();
  return <span>Lottery {record ? `"${record.ticketNumber}"` : ''}</span>;
};

export const LotteryList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="ticketNumber" />
      <DateField source="drawDate" />
      <NumberField source="prizeAmount" />
      <ReferenceField source="winner" reference="Players" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const LotteryEdit = () => (
  <Edit title={<LotteryTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="ticketNumber" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="drawDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="prizeAmount" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="winner" reference="Players" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const LotteryCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="ticketNumber" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="drawDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="prizeAmount" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="winner" reference="Players" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  <ReferenceInput
    source="winner"
    label="winner"
    reference="Players"
    alwaysOn
  />,
];
